import React from 'react';
import { ArrowLeft, Share2, CheckCircle2, Download } from 'lucide-react';
import { LeadStatus } from '../types';

interface Props {
  lead: LeadStatus;
  onBack: () => void;
}

const Action_ViewReceipt: React.FC<Props> = ({ lead, onBack }) => {
  return (
    <div className="h-full bg-gray-800 flex flex-col animate-fade-in text-white">
       {/* Header */}
      <div className="px-4 py-3 flex items-center gap-3">
        <button onClick={onBack} className="p-2 hover:bg-white/10 rounded-full">
          <ArrowLeft size={20} className="text-white" />
        </button>
        <div className="flex-1">
          <h2 className="font-bold">Transaction Receipt</h2>
        </div>
      </div>

      <div className="flex-1 p-6 flex flex-col items-center justify-center">
         
         {/* Receipt Card */}
         <div className="w-full bg-white text-gray-900 rounded-3xl overflow-hidden shadow-2xl relative">
            {/* Top Pattern */}
            <div className="h-2 bg-gradient-to-r from-[#97144d] to-[#e31e24]"></div>
            
            <div className="p-8 text-center border-b border-gray-100 border-dashed">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4 text-green-600">
                   <CheckCircle2 size={32} />
                </div>
                <h1 className="text-2xl font-bold text-gray-900">₹ {lead.amount}</h1>
                <p className="text-sm text-gray-500 mt-1">Loan Disbursed Successfully</p>
            </div>

            <div className="p-8 space-y-4">
               <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Date</span>
                  <span className="font-bold">{lead.date}</span>
               </div>
               <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Customer</span>
                  <span className="font-bold">{lead.customerName}</span>
               </div>
               <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Product</span>
                  <span className="font-bold">{lead.productName}</span>
               </div>
               <div className="flex justify-between text-sm">
                  <span className="text-gray-500">Ref ID</span>
                  <span className="font-mono text-gray-600 bg-gray-100 px-2 py-0.5 rounded">{lead.leadId}</span>
               </div>

               <div className="border-t border-gray-100 pt-4 mt-4">
                  <div className="flex justify-between items-center">
                     <span className="text-sm font-bold text-[#97144d]">Commission Earned</span>
                     <span className="text-lg font-bold text-green-600">+ ₹500.00</span>
                  </div>
               </div>
            </div>

            {/* Jagged Edge Bottom (CSS Trick) */}
            <div className="h-4 bg-gray-800" style={{clipPath: 'polygon(0 0, 5% 100%, 10% 0, 15% 100%, 20% 0, 25% 100%, 30% 0, 35% 100%, 40% 0, 45% 100%, 50% 0, 55% 100%, 60% 0, 65% 100%, 70% 0, 75% 100%, 80% 0, 85% 100%, 90% 0, 95% 100%, 100% 0)'}}></div>
         </div>

         <p className="text-xs text-gray-400 mt-6 text-center max-w-xs">
            This is a digital receipt generated by Axis Spice Banking Service Center.
         </p>

      </div>

      <div className="p-4 space-y-3">
         <button className="w-full bg-[#25D366] text-white py-4 rounded-xl font-bold text-lg shadow-lg flex items-center justify-center gap-2">
            <Share2 size={20} /> Share on WhatsApp
         </button>
         <button className="w-full bg-white/10 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2">
            <Download size={18} /> Download PDF
         </button>
      </div>
    </div>
  );
};

export default Action_ViewReceipt;